# game info # 
STATE_SHAPE = (9, 9) 
N_ACTIONS = STATE_SHAPE[0]*STATE_SHAPE[1]
ACTION_SPACE = range(N_ACTIONS)
WINNING_CONDITION = 5

# state info #
STATE_DIM = 4 # (2,3,4,5)
ALLOW_TRANSPOSE = True 
DATA_AGUMENTATION = True 

# count #
N_PLAYOUT = 400

# nn #
N_KERNEL = 128
N_RESIDUAL_BLOCK = 10
BATCH_SIZE = 512 